package com.jrvs.trading.traderAccount;

import com.jrvs.trading.ResponseExceptionUtil;
import com.jrvs.trading.account.Account;
import com.jrvs.trading.account.AccountDao;
import com.jrvs.trading.position.Position;
import com.jrvs.trading.position.PositionDao;
import com.jrvs.trading.securityOrder.SecurityOrderDao;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class TraderAccountService {

    TraderDao traderDao;
    AccountDao accountDao;
    PositionDao positionDao;
    SecurityOrderDao securityOrderDao;

    @Autowired
    public TraderAccountService(TraderDao traderDao, AccountDao accountDao, PositionDao positionDao, SecurityOrderDao securityOrderDao) {
        this.traderDao = traderDao;
        this.accountDao = accountDao;
        this.positionDao = positionDao;
        this.securityOrderDao = securityOrderDao;
    }
    /**
     * Create a new trader and initialize a new account with 0 amount
     * - validate user input (all fields must be non empty)
     * - create a trader
     * - create an account
     * - create, setup, and return a new traderAccountView
     *
     * Assumption: to simplify the logic, each trader has only one account where traderId == accountId
     *
     * @param trader cannot be null. All fields cannot be null except for id (auto-generated by db)
     * @return traderAccountView
     * @throws IllegalArgumentException if a trader has null fields or id is not null
     */
    public TraderAccountView createTraderAndAccount(Trader trader) {
        if(trader == null || trader.firstName == null || trader.country == null || trader.dob == null || trader.lastName == null || trader.email == null) {
            throw new IllegalArgumentException("Fields other than ID cannot be null");
        }

        Trader savedTrader = traderDao.save(trader);
        Account savedAccount = accountDao.save(new Account(trader.id, 0));

        return new TraderAccountView(
                savedTrader.id,
                savedAccount.getId(),
                savedTrader.firstName,
                savedTrader.lastName,
                savedAccount.getAmount(),
                savedTrader.dob,
                savedTrader.country,
                savedTrader.email
        );
    }

    /**
     * A trader can be deleted if and only if it has no open position and 0 cash balance
     * - validate traderId
     * - get trader account by traderId and check account balance
     * - get positions by accountId and check positions
     * - delete all securityOrders, account, trader (in this order)
     *
     * @param traderId must not be null
     * @throws IllegalArgumentException if traderId is null or not found or unable to delete
     */
    public void deleteTraderById(Integer traderId) {

        if(traderId == null) {
            throw new IllegalArgumentException("Trader id cannot be null.");
        }

        if(!traderDao.existsById(traderId)) {
            throw new IllegalArgumentException("Trader with given id does not exist.");
        }

        Account account = accountDao.getAccountByTraderId(traderId);

        if(account.getAmount() > 0) {
            throw new IllegalArgumentException("Cannot delete trader with funds in account.");
        }

//        List<Position> positions = new ArrayList<>();
//
//        if (positionDao.findByAccountIdEquals(account.getId()) != null) {
//            positions = positionDao.findByAccountIdEquals(account.getId());
//        }
//
//        if(!positions.isEmpty()) {
//            throw new IllegalArgumentException("Cannot delete trader with open positions.");
//        }

        securityOrderDao.deleteAllByAccountId(account.getId());
        accountDao.deleteById(account.getId());
        traderDao.deleteById(traderId);
    }

    /**
     * Deposit a fund to an account by traderId
     * - validate user input
     * - find account by trader id
     * - update the amount accordingly
     *
     * @param traderId must not be null
     * @param fund must be greater than 0
     * @return updated Account
     * @throws IllegalArgumentException if traderId is null or not found,
     * 									and fund is less than or equal to 0
     */
    public Account deposit(Integer traderId, Double fund) {

        if(traderId == null) {
            throw new IllegalArgumentException("Trader id cannot be null.");
        }

        if(fund == null || fund <= 0) {
            throw new IllegalArgumentException("You must deposit more than $0.");
        }

        Account account = accountDao.getAccountByTraderId(traderId);

        if(account == null) {
            throw new IllegalArgumentException("No account exists by the given trader id.");
        }

        account.setAmount(account.getAmount() + fund);

        return accountDao.save(account);
    }

    /**
     * Withdraw a fund to an account by traderId
     * - validate user input
     * - find account by trader id
     * - update the amount accordingly
     *
     * @param traderId must not be null
     * @param fund must be greater than 0
     * @return updated Account
     * @throws IllegalArgumentException if traderId is null or not found,
     * 									and fund is less than or equal to 0
     */
    public Account withdraw(Integer traderId, Double fund) {

        if(traderId == null) {
            throw new IllegalArgumentException("Trader id cannot be null.");
        }

        if(fund == null || fund <= 0) {
            throw new IllegalArgumentException("You must withdraw more than $0.");
        }

        Account account = accountDao.getAccountByTraderId(traderId);

        if(account == null) {
            throw new IllegalArgumentException("No account exists by the given trader id.");
        }

        if(account.getAmount() < fund) {
            throw new IllegalArgumentException("Insufficient funds.");
        }

        account.setAmount(account.getAmount() - fund);

        return accountDao.save(account);
    }
}
